remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: **Hello there! Here are three (3) things I like to do:**
description: Now here! Enjoy a random photo I took of a flower!
